---
name: Set environment
on:
  workflow_dispatch:
    inputs:
      FULL_RUN:
        description: 'Full run or not'
        type: boolean
        required: false
        default: false
jobs:
  set-env:
    runs-on: ubuntu-latest
    if: inputs.FULL_RUN
    steps:
      - run: |
        if [[ "${{ inputs.FULL_RUN }}" == 'false' ]]; then
          echo "Not FULL_RUN"
        fi
