---
name: Set environment
on:
  workflow_dispatch:
    inputs:
      GENERATE_TOKEN:
        description: 'Generate token or not'
        type: boolean
        required: false
        default: false
        
jobs:
  set-env:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        if: inputs.GENERATE_TOKEN
        run: |
          echo "token=abc" | tee -a $GITHUB_OUTPUT
      - uses: actions/checkout@v3
        with:
          token: "${{ steps.generate-token.outputs.token || github.token }}"
