---
name: Set environment
on:
  workflow_dispatch:
    inputs:
      TOKEN:
        description: 'A token'
        type: string
        required: false
        default: ""
        
jobs:
  set-env:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: "${{ inputs.TOKEN }}"
