---
name: Set environment
on:
  workflow_dispatch:
    inputs:
      FULL_RUN:
        description: 'Full run or not'
        type: boolean
        required: false
        default: false
        
jobs:
  set-env:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Check
        if: inputs.FULL_RUN
        run: echo "This is Full Run"
          
      - name: Print
        run: |
          if [[ "${{ inputs.FULL_RUN }}" == 'false' ]]; then
            echo "Not FULL_RUN"
          fi
