---
name: Deploy service
on:
  workflow_dispatch:
permissions:
  id-token: write
jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to staging
        run: |
          aws --version
  deploy-to-production:
    runs-on: ubuntu-latest
    needs: ['deploy-to-staging']
    environment: production
    steps:
      - name: Deploy to production
        run: |
          aws --version
